
$(this).find('[name="phone"]').each(function () {
    const phoneMultiMask = new window.PhoneMultiMask({
        input: this,
        codes: window.phoneCodes,
        defaultCountry: 'ge',
        geoCodeAuto: false,
        countrySort: [
            'ru',
            'ge',
            'by',
            'am',
            'de',
            'kz',
            'ua',
            'md',
            'us',
            'il',
            'az',
            'tr',
            'cn',
            'kg',
            'pl',
            'ee',
            'gb',
            'lt',
            'es',
            'fr',
            'nl',
            'uz',
            'bg',
            'cz',
            'ca',
            'se',
            'it',
            'fi',
            'lv',
            'gr',
            'be',
            'cy',
            'ch',
            'no',
            'rs',
            'me',
            'at',
            'kp',
            'th',
            'ro',
            'tj',
            'hu',
            'pt',
            'br',
            'sk',
            'in',
            'dk',
            'tm',
            'ir',
            'ae',
            'ab',
            'sg',
            'hr',
            'mx',
            'vn',
            'jp',
            'sa',
            'id',
            'si',
            'ie',
            'ar',
            'do',
            'eg',
            'ky',
            'ph',
            'qa',
            'mt',
            'ba',
            'my'
        ]
    });
});